<?php
/**
 * Loewenstark_Newsletter
 *
 * @category    design
 * @package     Loewenstark_Newsletter
 * @copyright   Copyright (c) 2012 Mathis Klooss (http://www.loewenstark.de/)
 * @license     https://github.com/mklooss/Loewenstark_Newsletter/blob/master/README.md
 */
?>
<div class="block block-subscribe block-unsubscribe">
    <div class="block-title">
        <strong><span><?php echo $this->__('Newsletter Unsubscribe') ?></span></strong>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-unsubscribe-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header form-unsubscribe-header">
                <label for="newsletter-unsubscribe"><?php echo $this->__('Unsubscribe Our Newsletter:') ?></label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter-unsubscribe" title="<?php echo $this->__('Unsubscribe Our Newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Unsubscribe') ?>" class="button"><span><span><?php echo $this->__('Unsubscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterUnsubscriberFormDetail = new VarienForm('newsletter-unsubscribe-validate-detail');
    //]]>
    </script>
</div>
